### ISSUE TITLE
DS4/Hori DIVA FT ASC Slider output mode doesn't work with Project DIVA Mega Mix+ (PC)

### ISSUE THREAD

**Issue by cainan-c** [4yn/slidershim#10]
Running slidershim 0.5 and tried using it with Mega Mix+ with the Arcade Controller mode enabled, doesn't seem to work at all.
It works somewhat in the UI but otherwise it's unusable.
![image](https://user-images.githubusercontent.com/30056568/209583062-9eed8019-b221-4792-a658-8c4234760719.png)
![image](https://user-images.githubusercontent.com/30056568/209583091-2c39ff22-d481-4a11-8c33-67addb9598e4.png)
Video of it in action https://cdn.discordapp.com/attachments/502204856623431681/1057040478979239976/IMG_7683.mov

**Comment by 4yn** [comment]
I don't own MegaMix+ so I'm unable to test on my side. I can only confirm that the HORI slider emulation works with TLAC. I suspect it may be issue with spoofing the device / vendor ID, which may not be possible using ViGEmBus and therefore may not be possible with slidershim right now.

If you know how to tweak it, feel free to drop a pull request some time.

**Comment by april83c** [comment]
did you figure out a fix for this?

**Comment by samnyan** [comment]
I made a mod to bypass the vid pid check, now it will work with MegaMix+ https://github.com/samnyan/AnySlider

**Comment by april83c** [comment]
> I made a mod to bypass the vid pid check, now it will work with MegaMix+ https://github.com/samnyan/AnySlider

thank you!! I had been using a janky script to emulate the VID and PID of the controller, now I can get rid of it - this is exactly the mod I wished existed
