### ISSUE TITLE
Unable to get Voltex/Neardayo output working with USC

### ISSUE THREAD

**Issue by scrib-bler** [4yn/slidershim#11]
When using the voltex/neardayo layouts, I can't get USC or spice2x to work.

When using the keyboard variants, I get the correct keyboard outputs in Notepad, but the games don't register.
When using controller outputs, I'm able to bind the controller buttons, but Left Stick/Right Stick aren't detected in USC.

Everything works fine with UMIGURI so I know both my controller and slidershim are capable of working.

I've tried running everything as admin too but no change.

Thanks!

**Comment by 4yn** [comment]
Inside USC's `Main.cfg`, can you set `Controller_DirectMode` to `True`. You need to edit the file with notepad, i don't think it can be changed from the in-game menu.

**Comment by scrib-bler** [comment]
Even with this setting changed I'm unable to get USC to detect keyboard keys when sent from my Tasoller via slidershim :(
Is there a way to edit the layouts? I'm able to use controller inputs for everything but the knobs, so if I could rebind the knobs in the Voltex layout to use buttons instead of sticks then I should be able to get it working.

Thanks

**Comment by 4yn** [comment]
Set slidershim to XBOX controller output modes. Double check that USC is configured to use the "XBOX 360 controller" and "Controller Laser Input Method" and that you've also made the `Controller_DirectMode` change I mentioned earlier. Oh, and you'll need to lower your knob sensitivity a lot.

![image](https://user-images.githubusercontent.com/8877057/236633936-ac1f6f26-be7d-417e-ac62-ed4dbe174a5d.png)

I've verified that it does work with my own setup of USC.
