### ISSUE TITLE
Brokenithm-iOS Support Hope

### ISSUE THREAD

**Issue by ZWolken** [4yn/slidershim#2]
Just hope to add [Brokenithm-iOS](https://github.com/esterTion/Brokenithm-iOS) input support.
Brokenithm-iOS just use the usb cable but not web to transfer the input data.
The iOS packed ipa can be download at https://redive.estertion.win/ipas/ and Windows exe file at https://redive.estertion.win/ipas/Brokenithm/
Thanks.

**Comment by 4yn** [comment]
I currently have no plans to support brokenithm using ipa controller or other types of communication over usb. Right now there is also poor rust support for libimobiledevice which makes it hard to implement. You are still welcome to fork slidershim and try implementing it.

One alternative way to reduce lag is to enable usb hotspot tethering which will theoretically run the web controller over the wired connection and reduce lag.
