### ISSUE TITLE
brokenithm-kb input mode port manual setting request

### ISSUE THREAD

**Issue by ZWolken** [4yn/slidershim#3]
As early in brokenithm-kb's issues said, the brokenithm-kb can't work on 1606 port on my computer (I don't no the reason), but when I switch it to some other port, it can successfully start up.
But turn back to slidershim, when I select brokenithm as input device, it can only listening to the 1606 port, so it get in trouble on my computer.
I just hope the future version can let me set the listening port manually.
Thanks a lot!

**Comment by 4yn** [comment]
I have added the option to change brokenithm port in the [latest release here](https://github.com/4yn/slidershim/releases/tag/v0.2.6), let me know if it works.

**Comment by ZWolken** [comment]
https://user-images.githubusercontent.com/76812845/160138793-e96ce679-1b46-46b0-8986-db59edbf05ef.mp4
Oops, the port change works well, but I haven't change any input key settings in segatools when brokenithm's input can't match with chuni's input.
The slider input from brokenithm is 642zxvtrpnljhfdb
The air is ;\][=-
Is this slidershim's or something else's reason?

**Comment by 4yn** [comment]
Please do not use illegal data with my software, i will be deleting this thread
