### ISSUE TITLE
Incorrect key assignment of UMIGURI layout

### ISSUE THREAD

**Issue by inonote** [4yn/slidershim#5]
I found a key assignment of slidershim's umiguri layout is incorrect.
The rightmost of the bottom row is assigned `VK_OEM_COMMA` in slidershim, but it should be assigned `'9'`.

![image](https://user-images.githubusercontent.com/32731693/175800787-54acd588-c514-4b81-b9eb-4142ad91522a.png)

**Comment by 4yn** [comment]
Oops, thanks for finding this mistake! I have fixed it in [0.3.1](https://github.com/4yn/slidershim/releases/tag/v0.3.1).
