### ISSUE TITLE
Diva slider layout issue

### ISSUE THREAD

**Issue by loren0127** [4yn/slidershim#6]
Hi There is a problem with the order of the Diva slider Layout In PDAFT. 
The program recognizes the input correctly, but the order of the outputs is messed up.
Please check the attached video link.
https://www.youtube.com/watch?v=bGPn3Gyj1r4

PS. I'm using a translator so I'm sorry if my English isn't good

**Comment by 4yn** [comment]
Thanks for the bug report. The video was very helpful.

I've fixed this in [v0.4.2](https://github.com/4yn/slidershim/releases/tag/v0.4.2).
