### ISSUE TITLE
YubiDeck USB protocol updated

### ISSUE THREAD

**Issue by DashLt** [4yn/slidershim#8]
Docs: https://zhousensor.notion.site/USB-c2905d560f25434a896b0bd12d1aa022

See downstream data protocol (下行数据结构(c语言)V3.0版本) for the changed struct.

Will hopefully have a translated version for you in the coming days.

**Comment by 4yn** [comment]
Don't need to rush the translated version, I can mostly understand what's going on.

For inputs, is `TouchValue[0]` still bottom left sensor? For lights, is `TouchArea[0]` still on the left side?

**Comment by DashLt** [comment]
Much appreciated. Neither ZhouSensor nor I can say for certain atm - I'd assume so, but testing is the best way to go.

**Comment by 4yn** [comment]
[It's done!](https://github.com/4yn/slidershim/releases/tag/v0.5.0)

**Comment by DashLt** [comment]
Thank you so much!
